name: Build my-resume project
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code in master
        uses: actions/checkout@master
      - name: setup nodeJs enviroment
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Install NPM dependencies
        run: npm install
      - name: Build project
        run: npm run build
